### ISSUE TITLE
缺少harbor-exporter:v2.6.0 

### ISSUE THREAD

**Issue by 631068264** [octohelm/harbor#369]
没有ghcr.io/octohelm/harbor/harbor-exporter:v2.6.0 ？  还是说那个harbor-exporter-base就是？不太明白base是什么

想问一下怎样针对某个镜像构建镜像？可以在x86环境编译吗？

使用离线包的安装话怎样替换镜像，替换哪些地方，还是直接改镜像名？

**Comment by morlay** [comment]
> 没有ghcr.io/octohelm/harbor/harbor-exporter:v2.6.0 ？ 还是说那个harbor-exporter-base就是？不太明白base是什么

base 是 各个组件的基础运行环境，没用过 exporter，所以应该是有地方没改到。

> 想问一下怎样针对某个镜像构建镜像？可以在x86环境编译吗？

可以，github actions 就是 x86_64 环境，详见 https://github.com/octohelm/harbor/blob/main/.github/workflows/docker-publish-images.yml

> 使用离线包的安装话怎样替换镜像，替换哪些地方，还是直接改镜像名？

是，替换就好了。 然后 `nerdctl save` 再 `load`，然后正常 helm 部署就是离线了。
