### ISSUE TITLE
harbor images for v2.8.0 

### ISSUE THREAD

**Issue by luckyluc74** [octohelm/harbor#430]
Great work btw, v2.7.0 running stable on my rpi4.

Would be nice to see octohelm arm64 harbor images for version v2.8.0

**Comment by morlay** [comment]
@luckyluc74 v2.8.2 ready

**Comment by luckyluc74** [comment]
@morlay thanks, appreciated!

**Comment by disconn3ct** [comment]
Notary server and signer don't appear to have built for 2.8.2.
