### ISSUE TITLE
notary-signer/notary-server  v2.8.2 buil failed

### ISSUE THREAD

**Issue by funnyfunny** [octohelm/harbor#432]
notary-signer/notary-server  v2.8.2 buil failed

https://github.com/octohelm/harbor/actions/runs/5354360642/job/14496055020

step: build & publish images

copy the binary files to local...
open /home/runner/work/harbor/harbor/harbor/make/photon/notary/binary/notary-server-linux-amd64: permission denied
+ echo 'building notary container for photon...'
building notary container for photon...
+ sudo chmod 655 '/home/runner/work/harbor/harbor/harbor/make/photon/notary/binary/notary-signer*'
chmod: cannot access '/home/runner/work/harbor/harbor/harbor/make/photon/notary/binary/notary-signer*': No such file or directory
+ sudo chmod 655 '/home/runner/work/harbor/harbor/harbor/make/photon/notary/binary/notary-server*'
chmod: cannot access '/home/runner/work/harbor/harbor/harbor/make/photon/notary/binary/notary-server*': No such file or directory
+ sudo rm -rf /home/runner/work/harbor/harbor/harbor/make/photon/notary/binary
+ echo Done.
Done.
make[1]: Leaving directory '/home/runner/work/harbor/harbor/harbor'

**Comment by morlay** [comment]
sudo issue.

use v2.8.3 with the fixed.

https://github.com/octohelm/harbor/pkgs/container/harbor%2Fnotary-signer-photon
https://github.com/octohelm/harbor/pkgs/container/harbor%2Fnotary-server-photon
