### ISSUE TITLE
Bump version to 2.9.0

### ISSUE THREAD

**Issue by samip5** [octohelm/harbor#433]
Hi @morlay could we please have an updated Harbor as the latest seems to be 2.9.0?

**Comment by morlay** [comment]
@samip5 Done https://github.com/octohelm/harbor/pkgs/container/harbor%2Fharbor-core

Notice, v2.9.0 dropped notary

**Comment by samip5** [comment]
> @samip5 Done https://github.com/octohelm/harbor/pkgs/container/harbor%2Fharbor-core

Seems to be missing multi-arch for redis?

```
Failed to pull image "ghcr.io/octohelm/harbor/redis-photon:v2.9.0": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/octohelm/harbor/redis-photon:v2.9.0": no match for platform in manifest: not found
```
