### ISSUE TITLE
Redis and db images for 2.9.0 seems to be lacking arm64

### ISSUE THREAD

**Issue by samip5** [octohelm/harbor#434]
Hi @morlay,

The following images seem to be missing arm64 platform in the pushed images to ghcr.io:

- ghcr.io/octohelm/harbor/harbor-db:v2.9.0
- ghcr.io/octohelm/harbor/redis-photon:v2.9.0

**Comment by morlay** [comment]
@samip5 building re-triggered.
https://github.com/octohelm/harbor/actions/runs/6217541680
May pull again about 10mins later.

Btw redis-photon not works on centos. you could use `docker/library/redis` instead.

**Comment by samip5** [comment]
> Btw redis-photon not works on centos

Not relevant to me.
