### ISSUE TITLE
Support Harbor 2.8.4 

### ISSUE THREAD

**Issue by jessehu** [octohelm/harbor#435]
Will 2.8.4 be supported? Thanks.
https://github.com/goharbor/harbor/releases/tag/v2.8.4

**Comment by morlay** [comment]
@jessehu 

No. 2.9.0 have alreay released. 
so old versions I will not to maintain.

You could pick the lastest commit from https://github.com/morlay/harbor/tree/patch-v2.8.3  
to build your self.
