### ISSUE TITLE
centos 运行./install.sh --with-trivy

### ISSUE THREAD

**Issue by enqi1** [octohelm/harbor#436]
Error response from daemon: driver failed programming external connectivity on endpoint harbor-log (f73cadf15f456358b579e76a3248754e5e452e55666d4853e3e0f50976e22e65): Bind for 127.0.0.1:1514 failed: port is already allocated

**Comment by enqi1** [comment]
> Error response from daemon: driver failed programming external connectivity on endpoint harbor-log (f73cadf15f456358b579e76a3248754e5e452e55666d4853e3e0f50976e22e65): Bind for 127.0.0.1:1514 failed: port is already allocated

netstat -lntp 和docker containerd ls -a没有发现有其他端口占用

**Comment by morlay** [comment]
dead os. never support
