### ISSUE TITLE
Update needed to 2.10 harbor

### ISSUE THREAD

**Issue by samip5** [octohelm/harbor#437]
Just before Christmas it was released. Please update.

https://github.com/goharbor/harbor/releases/tag/v2.10.0

**Comment by morlay** [comment]
@samip5 done

**Comment by disconn3ct** [comment]
Did it get unpublished?
https://github.com/octohelm/harbor/pkgs/container/harbor%2Fnotary-signer-photon/versions?filters%5Bversion_type%5D=tagged doesn't show it anymore

**Comment by samip5** [comment]
> Did it get unpublished? https://github.com/octohelm/harbor/pkgs/container/harbor%2Fnotary-signer-photon/versions?filters%5Bversion_type%5D=tagged doesn't show it anymore

Notary is no longer a part of it.
