### ISSUE TITLE
项目还更新吗？

### ISSUE THREAD

**Issue by super-vip** [octohelm/harbor#438]
从2.10.2到2.11.0，一直在守着跟进官方版本的amd64和arm64的发布。好像一直没法从 ghcr.io/octohelm/harbor 拉到新版镜像。

**Comment by morlay** [comment]
> 从2.10.2到2.11.0，一直在守着跟进官方版本的amd64和arm64的发布。好像一直没法从 ghcr.io/octohelm/harbor 拉到新版镜像。

有新版本需求提 issue，我没那么闲，会天天盯着一个基础组件有无更新
